version: "3.3"

services:
  frontend:
    build: ./frontend
    ports:
      - "70:5000"
    volumes:
      - ./frontend:/usr/src/app
    links:
      - backend
    networks: 
      - diagramnetwork
    stdin_open: true
    restart: always
        
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    networks: 
      - diagramnetwork
    restart: always

networks:
  diagramnetwork:
      driver: bridge