version: "3.3"

services:
  frontend:
    build: ./frontend
    ports:
      - "8082:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - backend
    networks: 
      - diagramnetwork      
    stdin_open: true
    restart: always
        
  backend:
    build: ./backend
    ports:
      - "8083:8080"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks: 
      - diagramnetwork
    restart: always
    
networks:
  diagramnetwork:
      driver: bridge